DWAPlannerROS:

  #Robot configuration Parameters
  acc_lim_x : 0.1
  acc_lim_y : 0.0
  acc_lim_th : 0.1

  #The velocity when robot is moving in a straight line
  max_vel_trans : 0.1
  min_vel_trans : 0.1

  max_vel_x : 0.1
  min_vel_x : -0.1

  max_vel_y : 0.0
  min_vel_y : 0.0

  max_rot_vel : 0.06
  min_rot_vel : 0.05


  #Goal Tolerance Parameters
  yaw_goal_tolerance : 0.05
  xy_goal_tolerance : 0.1
  latch_xy_goal_tolerance : false

  #Forward Simulation Parameters
  sim_time : 3
  sim_granularity : 0.025
  vx_samples : 8
  vy_samples : 0
  vth_samples : 20

  #Trajectory Scoring Parameters
  path_distance_bias : 25.0
  goal_distance_bias : 20.0
  occdist_scale : 0.02
  forward_point_distance : 0.325
  stop_time_buffer : 0.2
  scaling_speed : 0.25
  max_scaling_factor : 0.2

  #Oscillation Prevention Parameters
  oscillation_reset_dist : 0.05
  
  #Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true




  
