global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 5.0
   #width: 50.0
   #height: 50.0
   #resolution: 0.02
   static_map: true
   #rolling_window: false       
 
   transform_tolerance: 0.5 #v8
   plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"} #v8
    - {name: inflated_layer, type: "costmap_2d::InflationLayer"}