local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.05
  transform_tolerance: 0.5
  
  plugins:
            -  {name: obstacle_layer, type: "costmap_2d::ObstacleLayer", output: "screen"}
            -  {name: inflation_layer, type: "costmap_2d::InflationLayer", output: "screen"}

